# Generated by Django 4.2.13 on 2024-07-05 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='deadine',
            new_name='deadline',
        ),
    ]
