# Generated by Django 4.2.13 on 2024-07-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_topic_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
